### ISSUE TITLE
Allow me to upload to pypi

### ISSUE THREAD

**Issue by ghost** [ScientificPython/ScientificPython#8]

**Comment by khinsen** [comment]
Fine with me, but I am not sure what this requires technically. Currently there is MMTK-2.4.1 on PyPI which belongs to user "hinsen". This is attached to a no-longer-working e-mail address and I haven't been able to log in for a while for unknown reasons (perhaps the password I wrote down back then is not correct). So even I cannot upload a new version of MMTK to PyPI.

**Comment by ghost** [comment]
MMTK is not yet ready. I need to resolve the ScientificPython dependency first. Unfortunately it's not yet possible to recover a pypi account due to squabbling from PSF lawyers.

**Comment by ghost** [comment]
@ewdurbin Is it possible to recover his account?

**Comment by khinsen** [comment]
@ewdurbin Or transfer the ownership of the MMTK package to my new account PyPI `khinsen`? I think I can supply any required amount of proof that I am the lead author of MMTK!

**Comment by ghost** [comment]
@khinsen The warehouse issue was closed -- does this mean you have access?

**Comment by khinsen** [comment]
Yes. For reasons way beyond my understanding, I could login to my old account yesterday, using exactly the same password that had not worked for several months. I ended up transferring ownership of all projects to my new PyPI account "khinsen". One problem solved :-)

**Comment by ghost** [comment]
@khinsen You never gave me permission to upload ScientificPython wheels.

**Comment by khinsen** [comment]
Oops, sorry, I forgot about that. Done now, you are "maintainer" on ScientificPython.
